Repository Datawheel/canon, pull requests merged in 2019-10, with the labels that each got.

#699 Ap 10
  packages/cms/app/style.yml
  packages/cms/src/components/sections/InfoCard.css
  packages/cms/src/components/sections/InfoCard.jsx
  packages/cms/src/components/sections/Section.jsx
Labels: tweak

#755 removes anchor link offset from sticky section titles
  packages/cms/src/components/sections/Section.css
Labels: bug

#739 717 collapsible toolbox
  packages/cms/src/Builder.jsx
  packages/cms/src/components/Profile.jsx
  packages/cms/src/components/Viz/Options.css
  packages/cms/src/components/Viz/Table.css
  packages/cms/src/components/fields/Search.css
  packages/cms/src/components/interface/Deck.css
  packages/cms/src/components/interface/Toolbox.css
  packages/cms/src/components/interface/Toolbox.jsx
  packages/cms/src/components/sections/Section.css
  packages/cms/src/components/sections/Section.jsx
  packages/cms/src/components/variables/ConsoleVariable.css
  packages/cms/src/css/blueprint-overrides.css
  packages/cms/src/css/layout.css
  packages/cms/src/css/mixins.css
  packages/cms/src/css/utilities.css
  packages/cms/src/member/MetaEditor.css
  packages/cms/src/profile/ProfileBuilder.jsx
Labels: design, enhancement

#759 [vizbuilder/v0.3] fixes missing map in geo + unique cut queries
  packages/vizbuilder/src/helpers/chartHelpers.js
Labels: bug

#756 [cms] Performance Improvements
  packages/cms/src/Builder.jsx
  packages/cms/src/api/mortarRoute.js
  packages/cms/src/components/cards/GeneratorCard.jsx
  packages/cms/src/components/editors/QuillWrapper.jsx
  packages/cms/src/components/interface/Status.jsx
  packages/cms/src/components/interface/Toolbox.jsx
  packages/cms/src/profile/ProfileBuilder.jsx
  packages/cms/src/profile/SectionEditor.jsx
  packages/cms/src/utils/nestedObjectAssign.js
Labels: enhancement

#761 CDC fixes
  packages/cms/canon.js
  packages/cms/src/components/Profile.jsx
  packages/cms/src/components/Viz/ShareDirectLink.jsx
  packages/cms/src/components/Viz/Table.css
  packages/cms/src/components/sections/Section.jsx
  packages/cms/src/css/mixins.css
  packages/cms/src/utils/isIE.js
  src/i18n/canon.js
Labels: bug, chore

#788 styles var reset button
  packages/cms/src/components/Profile.jsx
  packages/cms/src/components/Viz/Viz.jsx
  packages/cms/src/components/cards/VisualizationCard.jsx
  packages/cms/src/components/fields/Button.jsx
  packages/cms/src/components/sections/Default.jsx
  packages/cms/src/components/sections/Grouping.jsx
  packages/cms/src/components/sections/InfoCard.css
  packages/cms/src/components/sections/InfoCard.jsx
  packages/cms/src/components/sections/MultiColumn.jsx
  packages/cms/src/components/sections/Section.css
  packages/cms/src/components/sections/Section.jsx
  packages/cms/src/components/sections/SingleColumn.jsx
  packages/cms/src/components/sections/Tabs.jsx
Labels: design

#791 CMS assorted bugfixes
  packages/cms/README.md
  packages/cms/api/testRoute.js
  packages/cms/package-lock.json
  packages/cms/package.json
  packages/cms/src/components/Profile.jsx
  packages/cms/src/components/Story.jsx
  packages/cms/src/components/Viz/Graphic.jsx
  packages/cms/src/components/Viz/Mirror.css
  packages/cms/src/components/Viz/Mirror.jsx
  packages/cms/src/components/Viz/Options.css
  packages/cms/src/components/Viz/Options.jsx
  packages/cms/src/components/Viz/PercentageBar.css
  packages/cms/src/components/Viz/PercentageBar.jsx
  packages/cms/src/components/Viz/ShareDirectLink.css
  packages/cms/src/components/Viz/ShareDirectLink.jsx
  packages/cms/src/components/Viz/StatGroup.css
  packages/cms/src/components/Viz/StatGroup.jsx
  packages/cms/src/components/Viz/Table.css
  packages/cms/src/components/Viz/Table.jsx
  packages/cms/src/components/Viz/Viz.css
  packages/cms/src/components/Viz/Viz.jsx
  packages/cms/src/components/Viz/defaultConfig.js
  packages/cms/src/components/fields/Button.css
  packages/cms/src/components/fields/Button.jsx
  packages/cms/src/components/fields/ButtonGroup.css
  packages/cms/src/components/fields/TextInput.css
  packages/cms/src/components/fields/TextInput.jsx
  packages/cms/src/components/sections/Default.css
  packages/cms/src/components/sections/Default.jsx
  packages/cms/src/components/sections/Hero.jsx
  packages/cms/src/components/sections/Section.jsx
  packages/cms/src/components/sections/Tabs.css
  packages/cms/src/components/sections/Tabs.jsx
  packages/cms/src/components/sections/components/Selector.jsx
  packages/cms/src/components/sections/components/Stat.jsx
  packages/cms/src/css/blueprint-overrides.css
  packages/cms/src/css/mixins.css
  packages/cms/src/member/MetaEditor.css
  packages/cms/src/utils/d3plusPropify.js
  packages/cms/src/utils/formatters/abbreviate.js
  packages/cms/src/utils/libs.js
Labels: bug, design

#796 improves generator speed by fixing nestedObjectAssign bug
  packages/cms/src/profile/ProfileBuilder.jsx
  packages/cms/src/utils/nestedObjectAssign.js
Labels: enhancement
