Repository Datawheel/canon, pull requests merged in 2020-07, with the labels that each got.

#1057 [cms] includes translations for texts on Table component
  packages/cms/src/components/Viz/Table.jsx
  packages/core/src/i18n/canon.js
Labels: bug, chore

#1063 [cms] improve search legacy API to support special chars fixed #1061
  packages/cms/README.md
  packages/cms/src/api/searchRoute.js
Labels: bug

#1069 feedback updates for warmup script
  packages/cms/scripts/warmup/cliRun.js
  packages/cms/scripts/warmup/cliScan.js
  packages/cms/scripts/warmup/consts.js
  packages/cms/scripts/warmup/index.js
  packages/cms/scripts/warmup/models.js
  packages/cms/scripts/warmup/workerPool.js
Labels: enhancement

#1071 add unaccent function to regular search query
  packages/cms/src/api/searchRoute.js
Labels: bug
