Repository Datawheel/canon, pull requests merged in 2021-02, with the labels that each got.

#1159 updates d3plus and d3 dependencies to next majors
  examples/package.json
  packages/cms/package.json
  packages/cms/src/components/fields/PreviewSearch.jsx
  packages/cms/src/components/fields/ProfileSearch.jsx
  packages/cms/src/components/fields/Search.jsx
  packages/core/package.json
  packages/logiclayer/package.json
  packages/vizbuilder/package.json
  pnpm-lock.yaml
Labels: enhancement

#1161 fixes d3plus nested dataFormat usage
  packages/cms/src/components/Viz/Viz.jsx
Labels: bug

#1162 removes unnecessary d3plus axis overrides
  packages/cms/src/utils/d3plusPropify.js
Labels: chore

#1163 uses nav-height and subnav-height to offset anchor link clicks
  packages/core/src/client.jsx
Labels: bug

#1164 fixes keyboard navigation for subsequent Options panel open/close
  packages/cms/src/components/Viz/Options.jsx
Labels: bug

#1170 Adds per-route HTTP status code support
  examples/app/routes.jsx
  examples/package.json
  packages/cms/package.json
  packages/core/package.json
  packages/core/src/server.jsx
  packages/logiclayer/package.json
  packages/vizbuilder/package.json
  pnpm-lock.yaml
Labels: enhancement

#1173 adds SubGrouping section type and SubNav behavior
  examples/api/cmsTestRoute.js
  examples/api/customAttributes.js
  examples/api/proxy.js
  examples/app/style.yml
  packages/cms/src/components/ProfileRenderer.jsx
  packages/cms/src/components/interface/Outline.css
  packages/cms/src/components/sections/Section.jsx
  packages/cms/src/components/sections/SubGrouping.jsx
  packages/cms/src/components/sections/components/Subnav.css
  packages/cms/src/components/sections/components/Subnav.jsx
  packages/cms/src/utils/sectionIconLookup.js
  packages/core/src/components/AnchorLink.jsx
Labels: enhancement
