Repository Datawheel/canon, pull requests merged in 2021-05, with the labels that each got.

#1204 [core/cms] anchor scroll and subnav behavior
  packages/cms/src/components/sections/components/Subnav.jsx
  packages/core/src/client.jsx
Labels: bug

#1207 [test] status API
  packages/cms/src/api/statusRoute.js
  packages/core/src/api/statusRoute.js
  packages/test/.env.example
  packages/test/README.md
  packages/test/package.json
  packages/test/src/index.js
  packages/test/src/tests/AppsChecker.js
  packages/test/src/tests/CommandsChecker.js
  packages/test/src/tests/ServicesChecker.js
  packages/test/src/utils/consts.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feature

#1212 Status api
  examples/package-lock.json
  packages/cms/src/api/statusRoute.js
  packages/core/src/api/statusRoute.js
  packages/test/package.json
  packages/test/src/app.js
  packages/test/src/index.js
  packages/test/src/public/normalize.css
  packages/test/src/public/styles.css
  packages/test/src/templates/partials/layout.liquid
  packages/test/src/templates/partials/result-block.liquid
  packages/test/src/templates/partials/result-item.liquid
  packages/test/src/templates/partials/status.liquid
  packages/test/src/templates/views/results.liquid
  packages/test/src/tests/AppsChecker.js
  packages/test/src/tests/CommandsChecker.js
  packages/test/src/tests/ServicesChecker.js
  pnpm-lock.yaml
Labels: enhancement

#1213 New associate in profile_meta model
  packages/cms/src/db/profile_meta.js
Labels: enhancement
