Repository Datawheel/canon, pull requests merged in 2021-08, with the labels that each got.

#1248 [core] preserves custom properties in transpiled CSS
  packages/core/webpack/config/postcss.js
Labels: type: enhancement, priority: 3 - medium, effort: 4 - easy

#1251 [core] login toast fix
  packages/cms/src/components/interface/LoginForm.jsx
  packages/core/src/auth/local.js
  packages/core/src/components/Login.jsx
Labels: type: bug, priority: 1 - urgent, effort: 3 - standard

#1250 [core] removes postcss-color-function and all color references in CSS
  examples/app/components/mixins.css
  examples/app/style.yml
  packages/cms/app/style.yml
  packages/cms/src/components/Showcase.css
  packages/cms/src/components/Viz/Table.css
  packages/cms/src/components/cards/Card.css
  packages/cms/src/components/editors/AceTheme.css
  packages/cms/src/components/editors/RichTextEditor.css
  packages/cms/src/components/fields/FilterSearch.css
  packages/cms/src/components/fields/PreviewSearch.css
  packages/cms/src/components/fields/ProfileTile.css
  packages/cms/src/components/fields/Select.css
  packages/cms/src/components/interface/Alert.css
  packages/cms/src/components/interface/AuthForm.css
  packages/cms/src/components/interface/Deck.css
  packages/cms/src/components/interface/Dialog.css
  packages/cms/src/components/interface/Dropdown.css
  packages/cms/src/components/interface/Navbar.css
  packages/cms/src/components/interface/Status.css
  packages/cms/src/components/sections/components/Subnav.css
  packages/cms/src/components/variables/ConsoleVariable.css
  packages/cms/src/css/base.css
  packages/cms/src/css/mixins.css
  packages/cms/src/member/MetaEditor.css
  packages/core/package.json
  packages/core/src/components/Forms.css
  packages/core/src/variables.css
  packages/core/webpack/config/postcss.js
  packages/create-canon/scaffold/app/style.yml
  pnpm-lock.yaml
Labels: type: bug, type: chore, priority: 1 - urgent, tag: breaking, effort: 3 - standard

#1253 Ignore terms in profile search #1252
  examples/app/pages/cms/Search.jsx
  packages/cms/README.md
  packages/cms/src/components/fields/ProfileSearch.jsx
Labels: type: enhancement
